name: e_commerce_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.0.0
  flutter_riverpod: ^2.4.0
  shimmer: ^3.0.0
  google_nav_bar: ^5.0.6
  badges: ^3.1.2
  firebase_core: ^2.17.0
  cloud_firestore: ^4.9.3
  firebase_auth: ^4.10.1
  flutter_facebook_auth: ^6.0.2
  google_sign_in: ^6.1.5
  equatable: ^2.0.5
  http: ^1.1.0
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  firebase_storage: ^11.2.8
  get_it: ^7.6.4



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/


